name: Manual Maven Release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: A custom version string
        required: false
        default: 'default'
      stage:
        type: boolean
        description: Whether to stage this release
        required: false
        default: false

jobs:
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      
      - name: Update version
        if: ${{ inputs.version != 'default' }}
        run: 'mvn versions:set -DnewVersion=${{ inputs.version }}'

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1.4.0
        with:
          maven_args: "-Dstage=${{ inputs.stage }}"
          maven_profiles: sources-and-javadoc,sign-and-deploy
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
